const ResumeApi = [
  {
    id: 1,
    category: "education",
    year: "BAL JYOTI PUBLIC SCHOOL(2011 - 2012)",
    image: "https://static.wixstatic.com/media/572899_e20fb8f7497f46bb89a972a2d66a4b55~mv2.png",
    title: "Secondary School",
    desc: "The education should be very interactual. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante.",
    rate: "6.6/10",
  },
  {
    id: 2,
    category: "education",
    year: "DEHRADUN PUBLIC SCHOOL(2012 - 2013) ",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJfYtA-ZFAf-q_kzbYdFsScEAe3F9yPFCv4BUC2wcKLQ&s",
    title: "Higher Secondary School",
    desc: "I have completed my 12th standard with physycs , chemistry , maths",
    rate: "71/100",
  },
  {
    id: 3,
    category: "education",
    year: "Dr APJ Abdul Kalam Technical University, Lucknow (2013 - 2017) ",
    image: "https://aktu.ac.in/images/uptu_logo.png",
    title: "Btech (Electrical and electronics engineering)",
    desc: "i have completed my gratuation in 2017",
    rate: "70/100 ",
  },
  {
    id: 4,
    category: "experience",
    image: "https://image3.mouthshut.com/images/imagesp/925995346s.png",
    year: "Orangus india pvt ltd(Nov,2019 - June,2020) ",
    title: "Full stack developer",
    desc: "My duty to develop web pages with the technology html5, css3, javascript, bootstrap4, photoshop",
    rate: "***",
  },
  {
    id: 5,
    category: "experience",
    image: "https://media-exp1.licdn.com/dms/image/C560BAQE7wMSNl5gq6g/company-logo_200_200/0/1589810956186?e=2147483647&v=beta&t=oTcL3TtYefVwI08qOAxbF5yvyKOP95zs0uW0wxQjHCA",
    year: "Dataviv Technologies(Aug,2020 - Oct,2021) ",
    title: "UI Developer and Wordpress Theme Builder",
    desc: "My duty to develop web pages with the technology html5, css3, javascript, bootstrap4, photoshop,and also build page on Wordpress also",
    rate: " *** ",
  },
  {
    id: 6,
    category: "experience",
    image: "https://media-exp1.licdn.com/dms/image/C510BAQHxI2qqHouDyw/company-logo_200_200/0/1545551840080?e=2147483647&v=beta&t=MvyuiW3nVRnYDSUwaJFukdu_Ckbn3a5SmBbc8MvlYUs",
    year: "Triedge.in(Oct,2021 - Dec,2021) ",
    title: "UI Developer",
    desc: "My duty to develop web pages with the technology html5, css3, javascript, bootstrap4, photoshop",
    rate: "***",
  },
  {
    id: 6,
    category: "experience",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSB8HtEEejUNyTOkdHpyoKXpkaArHJ3XLgG_i3CNMNB&s",
    year: "IDC Technologies(jan,2022 - Present) ",
    title: "UI Developer",
    desc: "My duty to develop web pages with the technology html5, css3, javascript, bootstrap4, photoshop",
    rate: "***",
  },
  {
    id: 7,
    category: "experience",
    image: "https://media.licdn.com/dms/image/C4E0BAQGDpEOuGqQlDA/company-logo_200_200/0/1653455836698/quaratechnologypvtltd_logo?e=2147483647&v=beta&t=dg63MwT4Y3K_tdvmGhXHgzQWomJDsN3tOahShT_kq78",
    year: "Quara Digital(jan,2023 - Present) ",
    title: "UI Developer",
    desc: "My duty to develop web pages with the technology html5, css3, javascript, bootstrap4, photoshop",
    rate: "***",
  },
]

export default ResumeApi
